// Copyright 2020 Eryx <evorui аt gmail dοt com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: kvfs.proto

package kvfs

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type KvFsMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path  string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size  int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Attrs uint64 `protobuf:"varint,4,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Mode  uint32 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Ctime int64  `protobuf:"varint,6,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime int64  `protobuf:"varint,7,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Atime int64  `protobuf:"varint,8,opt,name=atime,proto3" json:"atime,omitempty"`
}

func (x *KvFsMeta) Reset() {
	*x = KvFsMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvFsMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvFsMeta) ProtoMessage() {}

func (x *KvFsMeta) ProtoReflect() protoreflect.Message {
	mi := &file_kvfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvFsMeta.ProtoReflect.Descriptor instead.
func (*KvFsMeta) Descriptor() ([]byte, []int) {
	return file_kvfs_proto_rawDescGZIP(), []int{0}
}

func (x *KvFsMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KvFsMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *KvFsMeta) GetAttrs() uint64 {
	if x != nil {
		return x.Attrs
	}
	return 0
}

func (x *KvFsMeta) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *KvFsMeta) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *KvFsMeta) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *KvFsMeta) GetAtime() int64 {
	if x != nil {
		return x.Atime
	}
	return 0
}

type KvFsChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num  uint32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// int64 size = 3;
	Attrs uint64 `protobuf:"varint,4,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Data  []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *KvFsChunk) Reset() {
	*x = KvFsChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvFsChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvFsChunk) ProtoMessage() {}

func (x *KvFsChunk) ProtoReflect() protoreflect.Message {
	mi := &file_kvfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvFsChunk.ProtoReflect.Descriptor instead.
func (*KvFsChunk) Descriptor() ([]byte, []int) {
	return file_kvfs_proto_rawDescGZIP(), []int{1}
}

func (x *KvFsChunk) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *KvFsChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KvFsChunk) GetAttrs() uint64 {
	if x != nil {
		return x.Attrs
	}
	return 0
}

func (x *KvFsChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_kvfs_proto protoreflect.FileDescriptor

var file_kvfs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x76, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x76,
	0x66, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x08, 0x4b, 0x76, 0x46, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x09, 0x4b, 0x76, 0x46, 0x73, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x0a, 0x48, 0x03, 0x5a, 0x06, 0x2e, 0x3b, 0x6b, 0x76, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kvfs_proto_rawDescOnce sync.Once
	file_kvfs_proto_rawDescData = file_kvfs_proto_rawDesc
)

func file_kvfs_proto_rawDescGZIP() []byte {
	file_kvfs_proto_rawDescOnce.Do(func() {
		file_kvfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_kvfs_proto_rawDescData)
	})
	return file_kvfs_proto_rawDescData
}

var file_kvfs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kvfs_proto_goTypes = []interface{}{
	(*KvFsMeta)(nil),  // 0: kvfs.KvFsMeta
	(*KvFsChunk)(nil), // 1: kvfs.KvFsChunk
}
var file_kvfs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kvfs_proto_init() }
func file_kvfs_proto_init() {
	if File_kvfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kvfs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvFsMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvfs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvFsChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kvfs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kvfs_proto_goTypes,
		DependencyIndexes: file_kvfs_proto_depIdxs,
		MessageInfos:      file_kvfs_proto_msgTypes,
	}.Build()
	File_kvfs_proto = out.File
	file_kvfs_proto_rawDesc = nil
	file_kvfs_proto_goTypes = nil
	file_kvfs_proto_depIdxs = nil
}
